name: Linux SysAdmin CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make & Test Scripts
      run: |
        cat -A -T Makefile  # Debug TAB
        chmod +x *.sh
        ls -la *.sh  # 確認權限
        make test
